package com.kie_pract.bsat_1734;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Dealer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private int dlr_SCH_ID;
	private int dlr_FIN_AN_FLAG;
	private java.lang.String dlr_REGN;
	private java.lang.String dlr_DEPOT;
	private java.lang.String dlr_STATE;
	private java.lang.String dlr_TERR_CODE;
	private java.lang.String dlr_TERR_NAME;
	private java.lang.String dlr_BILL_TO;
	private java.lang.String dlr_AC_NO;
	private java.lang.String dlr_AC_NAME;
	private java.lang.String dlr_TYPE;
	private java.lang.String dlr_RET;
	private int dlr_TOT_CN;
	private int dlr_TOT_BDGT;
	private java.lang.String dlr_MAIN_STATUS;
	private double del_TY_VOLUME;
	private int dlr_MAIN_CN;
	private boolean dlr_RULES_AND_CONDITION;
	private boolean dlr_INFORMATION_IS_COLLECTED;
	private java.lang.String dlr_TERR;
	private java.lang.String dlr_SDLR_COUNT;
	private boolean dell_Col;
	private java.lang.String dlr_CAT;

	private java.util.List<com.kie_pract.bsat_1734.Product> productList;

	private boolean dlr_prd_ELIGIBLE_LY;

	private boolean rw_CODE;

	private java.lang.String rw_CODE_1;

	private java.lang.String rw_CODE_2;

	private java.lang.String rw_2_SEC;

	private java.lang.String rw_2_TYPE;

	private java.lang.String rw_2_PRD;

	private java.lang.String rw_2_UNIT;

	private java.lang.String rw_2_DATE;

	private java.lang.String rw_2_TGT;

	private java.lang.String rw_2_TY;

	private double rw_2_NXT_TGT;

	private java.lang.String rw_2_Q_STAT;

	private java.lang.String rw_1_ADDITIONAL;

	private java.lang.String rw_1_BASE_TOTAL;

	private java.lang.String rw_1_CONV_CN;

	private java.lang.String rw_1_DATE;

	private java.lang.String rw_1_DESC;

	private java.lang.String rw_1_DLR_BILL_TO;

	private java.lang.String rw_1_DLR_CAT;

	private java.lang.String rw_1_DLR_CODE;

	private java.lang.String rw_1_DLR_DEPOT;

	private java.lang.String rw_1_DLR_REGN;

	private java.lang.String rw_1_DLR_NAME;

	private java.lang.String rw_1_DLR_STATE;

	private java.lang.String rw_1_DLR_TERR_CODE;

	private java.lang.String rw_1_DLR_TERR_NAME;

	private java.lang.String rw_1_DLR_TYPE;

	private java.lang.String rw_1_GFT_ID;

	private java.lang.String rw_1_GFT_TO_CN;

	private java.lang.String rw_1_I_STAT;

	private java.lang.String rw_1_LAST_UPDATE;

	private java.lang.String rw_1_SCH_ID;

	private java.lang.String rw_1_PRD;

	private java.lang.String rw_1_LY;

	private java.lang.String rw_1_Q_STAT;

	private double rw_1_NXT_TGT;

	private java.lang.String rw_1_SEC;

	private java.lang.String rw_1_TGT;

	private java.lang.String rw_1_TY;

	private java.lang.String rw_1_TOTAL;

	private java.lang.String rw_2_CONV_CN;

	private java.lang.String rw_2_DESC;

	private java.lang.String rw_2_DLR_BILL_TO;

	private java.lang.String rw_2_DLR_CAT;

	private java.lang.String rw_2_DLR_CODE;

	private java.lang.String rw_2_CAT;

	private java.lang.String rw_2_CODE;

	private java.lang.String rw_2_DLR_DEPOT;

	private java.lang.String rw_2_DLR_NAME;

	private java.lang.String rw_2_DLR_REGN;

	private java.lang.String rw_2_DLR_STATE;

	private java.lang.String rw_2_DLR_TERR_CODE;

	private java.lang.String rw_2_DLR_TERR_NAME;

	private java.lang.String rw_2_DLR_TYPE;

	private java.lang.String rw_2_GFT_ID;

	private java.lang.String rw_2_GFT_TO_CN;

	private java.lang.String rw_2_I_STAT;

	private java.lang.String rw_2_LAST_UPDATE;

	private java.lang.String rw_2_LY;

	private java.lang.String rw_2_SCH_ID;

	private java.lang.String rw_2_TOTAL;

	private boolean dlr_prd_ELIGIBLE_TY;

	private java.lang.String rw_1_TYPE;

	private java.lang.String rw_1_UNIT;

	private java.lang.String rw_2_ADDITIONAL;

	public Dealer() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public int getDlr_SCH_ID() {
		return this.dlr_SCH_ID;
	}

	public void setDlr_SCH_ID(int dlr_SCH_ID) {
		this.dlr_SCH_ID = dlr_SCH_ID;
	}

	public int getDlr_FIN_AN_FLAG() {
		return this.dlr_FIN_AN_FLAG;
	}

	public void setDlr_FIN_AN_FLAG(int dlr_FIN_AN_FLAG) {
		this.dlr_FIN_AN_FLAG = dlr_FIN_AN_FLAG;
	}

	public java.lang.String getDlr_REGN() {
		return this.dlr_REGN;
	}

	public void setDlr_REGN(java.lang.String dlr_REGN) {
		this.dlr_REGN = dlr_REGN;
	}

	public java.lang.String getDlr_DEPOT() {
		return this.dlr_DEPOT;
	}

	public void setDlr_DEPOT(java.lang.String dlr_DEPOT) {
		this.dlr_DEPOT = dlr_DEPOT;
	}

	public java.lang.String getDlr_STATE() {
		return this.dlr_STATE;
	}

	public void setDlr_STATE(java.lang.String dlr_STATE) {
		this.dlr_STATE = dlr_STATE;
	}

	public java.lang.String getDlr_TERR_CODE() {
		return this.dlr_TERR_CODE;
	}

	public void setDlr_TERR_CODE(java.lang.String dlr_TERR_CODE) {
		this.dlr_TERR_CODE = dlr_TERR_CODE;
	}

	public java.lang.String getDlr_TERR_NAME() {
		return this.dlr_TERR_NAME;
	}

	public void setDlr_TERR_NAME(java.lang.String dlr_TERR_NAME) {
		this.dlr_TERR_NAME = dlr_TERR_NAME;
	}

	public java.lang.String getDlr_BILL_TO() {
		return this.dlr_BILL_TO;
	}

	public void setDlr_BILL_TO(java.lang.String dlr_BILL_TO) {
		this.dlr_BILL_TO = dlr_BILL_TO;
	}

	public java.lang.String getDlr_AC_NO() {
		return this.dlr_AC_NO;
	}

	public void setDlr_AC_NO(java.lang.String dlr_AC_NO) {
		this.dlr_AC_NO = dlr_AC_NO;
	}

	public java.lang.String getDlr_AC_NAME() {
		return this.dlr_AC_NAME;
	}

	public void setDlr_AC_NAME(java.lang.String dlr_AC_NAME) {
		this.dlr_AC_NAME = dlr_AC_NAME;
	}

	public java.lang.String getDlr_TYPE() {
		return this.dlr_TYPE;
	}

	public void setDlr_TYPE(java.lang.String dlr_TYPE) {
		this.dlr_TYPE = dlr_TYPE;
	}

	public java.lang.String getDlr_RET() {
		return this.dlr_RET;
	}

	public void setDlr_RET(java.lang.String dlr_RET) {
		this.dlr_RET = dlr_RET;
	}

	public int getDlr_TOT_CN() {
		return this.dlr_TOT_CN;
	}

	public void setDlr_TOT_CN(int dlr_TOT_CN) {
		this.dlr_TOT_CN = dlr_TOT_CN;
	}

	public int getDlr_TOT_BDGT() {
		return this.dlr_TOT_BDGT;
	}

	public void setDlr_TOT_BDGT(int dlr_TOT_BDGT) {
		this.dlr_TOT_BDGT = dlr_TOT_BDGT;
	}

	public java.lang.String getDlr_MAIN_STATUS() {
		return this.dlr_MAIN_STATUS;
	}

	public void setDlr_MAIN_STATUS(java.lang.String dlr_MAIN_STATUS) {
		this.dlr_MAIN_STATUS = dlr_MAIN_STATUS;
	}

	public int getDlr_MAIN_CN() {
		return this.dlr_MAIN_CN;
	}

	public void setDlr_MAIN_CN(int dlr_MAIN_CN) {
		this.dlr_MAIN_CN = dlr_MAIN_CN;
	}

	public boolean isDlr_RULES_AND_CONDITION() {
		return this.dlr_RULES_AND_CONDITION;
	}

	public void setDlr_RULES_AND_CONDITION(boolean dlr_RULES_AND_CONDITION) {
		this.dlr_RULES_AND_CONDITION = dlr_RULES_AND_CONDITION;
	}

	public boolean isDlr_INFORMATION_IS_COLLECTED() {
		return this.dlr_INFORMATION_IS_COLLECTED;
	}

	public void setDlr_INFORMATION_IS_COLLECTED(
			boolean dlr_INFORMATION_IS_COLLECTED) {
		this.dlr_INFORMATION_IS_COLLECTED = dlr_INFORMATION_IS_COLLECTED;
	}

	public java.lang.String getDlr_TERR() {
		return this.dlr_TERR;
	}

	public void setDlr_TERR(java.lang.String dlr_TERR) {
		this.dlr_TERR = dlr_TERR;
	}

	public java.lang.String getDlr_SDLR_COUNT() {
		return this.dlr_SDLR_COUNT;
	}

	public void setDlr_SDLR_COUNT(java.lang.String dlr_SDLR_COUNT) {
		this.dlr_SDLR_COUNT = dlr_SDLR_COUNT;
	}

	public boolean isDell_Col() {
		return this.dell_Col;
	}

	public void setDell_Col(boolean dell_Col) {
		this.dell_Col = dell_Col;
	}

	public java.lang.String getDlr_CAT() {
		return this.dlr_CAT;
	}

	public void setDlr_CAT(java.lang.String dlr_CAT) {
		this.dlr_CAT = dlr_CAT;
	}

	public java.util.List<com.kie_pract.bsat_1734.Product> getProductList() {
		return this.productList;
	}

	public void setProductList(
			java.util.List<com.kie_pract.bsat_1734.Product> productList) {
		this.productList = productList;
	}

	public boolean isDlr_prd_ELIGIBLE_LY() {
		return this.dlr_prd_ELIGIBLE_LY;
	}

	public void setDlr_prd_ELIGIBLE_LY(boolean dlr_prd_ELIGIBLE_LY) {
		this.dlr_prd_ELIGIBLE_LY = dlr_prd_ELIGIBLE_LY;
	}

	public boolean isRw_CODE() {
		return this.rw_CODE;
	}

	public void setRw_CODE(boolean rw_CODE) {
		this.rw_CODE = rw_CODE;
	}

	public java.lang.String getRw_CODE_1() {
		return this.rw_CODE_1;
	}

	public void setRw_CODE_1(java.lang.String rw_CODE_1) {
		this.rw_CODE_1 = rw_CODE_1;
	}

	public java.lang.String getRw_CODE_2() {
		return this.rw_CODE_2;
	}

	public void setRw_CODE_2(java.lang.String rw_CODE_2) {
		this.rw_CODE_2 = rw_CODE_2;
	}

	public double getDel_TY_VOLUME() {
		return this.del_TY_VOLUME;
	}

	public void setDel_TY_VOLUME(double del_TY_VOLUME) {
		this.del_TY_VOLUME = del_TY_VOLUME;
	}

	public java.lang.String getRw_2_SEC() {
		return this.rw_2_SEC;
	}

	public void setRw_2_SEC(java.lang.String rw_2_SEC) {
		this.rw_2_SEC = rw_2_SEC;
	}

	public java.lang.String getRw_2_TYPE() {
		return this.rw_2_TYPE;
	}

	public void setRw_2_TYPE(java.lang.String rw_2_TYPE) {
		this.rw_2_TYPE = rw_2_TYPE;
	}

	public java.lang.String getRw_2_PRD() {
		return this.rw_2_PRD;
	}

	public void setRw_2_PRD(java.lang.String rw_2_PRD) {
		this.rw_2_PRD = rw_2_PRD;
	}

	public java.lang.String getRw_2_UNIT() {
		return this.rw_2_UNIT;
	}

	public void setRw_2_UNIT(java.lang.String rw_2_UNIT) {
		this.rw_2_UNIT = rw_2_UNIT;
	}

	public java.lang.String getRw_2_DATE() {
		return this.rw_2_DATE;
	}

	public void setRw_2_DATE(java.lang.String rw_2_DATE) {
		this.rw_2_DATE = rw_2_DATE;
	}

	public java.lang.String getRw_2_TGT() {
		return this.rw_2_TGT;
	}

	public void setRw_2_TGT(java.lang.String rw_2_TGT) {
		this.rw_2_TGT = rw_2_TGT;
	}

	public java.lang.String getRw_2_TY() {
		return this.rw_2_TY;
	}

	public void setRw_2_TY(java.lang.String rw_2_TY) {
		this.rw_2_TY = rw_2_TY;
	}

	public double getRw_2_NXT_TGT() {
		return this.rw_2_NXT_TGT;
	}

	public void setRw_2_NXT_TGT(double rw_2_NXT_TGT) {
		this.rw_2_NXT_TGT = rw_2_NXT_TGT;
	}

	public java.lang.String getRw_2_Q_STAT() {
		return this.rw_2_Q_STAT;
	}

	public void setRw_2_Q_STAT(java.lang.String rw_2_Q_STAT) {
		this.rw_2_Q_STAT = rw_2_Q_STAT;
	}

	public java.lang.String getRw_1_ADDITIONAL() {
		return this.rw_1_ADDITIONAL;
	}

	public void setRw_1_ADDITIONAL(java.lang.String rw_1_ADDITIONAL) {
		this.rw_1_ADDITIONAL = rw_1_ADDITIONAL;
	}

	public java.lang.String getRw_1_BASE_TOTAL() {
		return this.rw_1_BASE_TOTAL;
	}

	public void setRw_1_BASE_TOTAL(java.lang.String rw_1_BASE_TOTAL) {
		this.rw_1_BASE_TOTAL = rw_1_BASE_TOTAL;
	}

	public java.lang.String getRw_1_CONV_CN() {
		return this.rw_1_CONV_CN;
	}

	public void setRw_1_CONV_CN(java.lang.String rw_1_CONV_CN) {
		this.rw_1_CONV_CN = rw_1_CONV_CN;
	}

	public java.lang.String getRw_1_DATE() {
		return this.rw_1_DATE;
	}

	public void setRw_1_DATE(java.lang.String rw_1_DATE) {
		this.rw_1_DATE = rw_1_DATE;
	}

	public java.lang.String getRw_1_DESC() {
		return this.rw_1_DESC;
	}

	public void setRw_1_DESC(java.lang.String rw_1_DESC) {
		this.rw_1_DESC = rw_1_DESC;
	}

	public java.lang.String getRw_1_DLR_BILL_TO() {
		return this.rw_1_DLR_BILL_TO;
	}

	public void setRw_1_DLR_BILL_TO(java.lang.String rw_1_DLR_BILL_TO) {
		this.rw_1_DLR_BILL_TO = rw_1_DLR_BILL_TO;
	}

	public java.lang.String getRw_1_DLR_CAT() {
		return this.rw_1_DLR_CAT;
	}

	public void setRw_1_DLR_CAT(java.lang.String rw_1_DLR_CAT) {
		this.rw_1_DLR_CAT = rw_1_DLR_CAT;
	}

	public java.lang.String getRw_1_DLR_CODE() {
		return this.rw_1_DLR_CODE;
	}

	public void setRw_1_DLR_CODE(java.lang.String rw_1_DLR_CODE) {
		this.rw_1_DLR_CODE = rw_1_DLR_CODE;
	}

	public java.lang.String getRw_1_DLR_DEPOT() {
		return this.rw_1_DLR_DEPOT;
	}

	public void setRw_1_DLR_DEPOT(java.lang.String rw_1_DLR_DEPOT) {
		this.rw_1_DLR_DEPOT = rw_1_DLR_DEPOT;
	}

	public java.lang.String getRw_1_DLR_REGN() {
		return this.rw_1_DLR_REGN;
	}

	public void setRw_1_DLR_REGN(java.lang.String rw_1_DLR_REGN) {
		this.rw_1_DLR_REGN = rw_1_DLR_REGN;
	}

	public java.lang.String getRw_1_DLR_NAME() {
		return this.rw_1_DLR_NAME;
	}

	public void setRw_1_DLR_NAME(java.lang.String rw_1_DLR_NAME) {
		this.rw_1_DLR_NAME = rw_1_DLR_NAME;
	}

	public java.lang.String getRw_1_DLR_STATE() {
		return this.rw_1_DLR_STATE;
	}

	public void setRw_1_DLR_STATE(java.lang.String rw_1_DLR_STATE) {
		this.rw_1_DLR_STATE = rw_1_DLR_STATE;
	}

	public java.lang.String getRw_1_DLR_TERR_CODE() {
		return this.rw_1_DLR_TERR_CODE;
	}

	public void setRw_1_DLR_TERR_CODE(java.lang.String rw_1_DLR_TERR_CODE) {
		this.rw_1_DLR_TERR_CODE = rw_1_DLR_TERR_CODE;
	}

	public java.lang.String getRw_1_DLR_TERR_NAME() {
		return this.rw_1_DLR_TERR_NAME;
	}

	public void setRw_1_DLR_TERR_NAME(java.lang.String rw_1_DLR_TERR_NAME) {
		this.rw_1_DLR_TERR_NAME = rw_1_DLR_TERR_NAME;
	}

	public java.lang.String getRw_1_DLR_TYPE() {
		return this.rw_1_DLR_TYPE;
	}

	public void setRw_1_DLR_TYPE(java.lang.String rw_1_DLR_TYPE) {
		this.rw_1_DLR_TYPE = rw_1_DLR_TYPE;
	}

	public java.lang.String getRw_1_GFT_ID() {
		return this.rw_1_GFT_ID;
	}

	public void setRw_1_GFT_ID(java.lang.String rw_1_GFT_ID) {
		this.rw_1_GFT_ID = rw_1_GFT_ID;
	}

	public java.lang.String getRw_1_GFT_TO_CN() {
		return this.rw_1_GFT_TO_CN;
	}

	public void setRw_1_GFT_TO_CN(java.lang.String rw_1_GFT_TO_CN) {
		this.rw_1_GFT_TO_CN = rw_1_GFT_TO_CN;
	}

	public java.lang.String getRw_1_I_STAT() {
		return this.rw_1_I_STAT;
	}

	public void setRw_1_I_STAT(java.lang.String rw_1_I_STAT) {
		this.rw_1_I_STAT = rw_1_I_STAT;
	}

	public java.lang.String getRw_1_LAST_UPDATE() {
		return this.rw_1_LAST_UPDATE;
	}

	public void setRw_1_LAST_UPDATE(java.lang.String rw_1_LAST_UPDATE) {
		this.rw_1_LAST_UPDATE = rw_1_LAST_UPDATE;
	}

	public java.lang.String getRw_1_SCH_ID() {
		return this.rw_1_SCH_ID;
	}

	public void setRw_1_SCH_ID(java.lang.String rw_1_SCH_ID) {
		this.rw_1_SCH_ID = rw_1_SCH_ID;
	}

	public java.lang.String getRw_1_PRD() {
		return this.rw_1_PRD;
	}

	public void setRw_1_PRD(java.lang.String rw_1_PRD) {
		this.rw_1_PRD = rw_1_PRD;
	}

	public java.lang.String getRw_1_LY() {
		return this.rw_1_LY;
	}

	public void setRw_1_LY(java.lang.String rw_1_LY) {
		this.rw_1_LY = rw_1_LY;
	}

	public java.lang.String getRw_1_Q_STAT() {
		return this.rw_1_Q_STAT;
	}

	public void setRw_1_Q_STAT(java.lang.String rw_1_Q_STAT) {
		this.rw_1_Q_STAT = rw_1_Q_STAT;
	}

	public double getRw_1_NXT_TGT() {
		return this.rw_1_NXT_TGT;
	}

	public void setRw_1_NXT_TGT(double rw_1_NXT_TGT) {
		this.rw_1_NXT_TGT = rw_1_NXT_TGT;
	}

	public java.lang.String getRw_1_SEC() {
		return this.rw_1_SEC;
	}

	public void setRw_1_SEC(java.lang.String rw_1_SEC) {
		this.rw_1_SEC = rw_1_SEC;
	}

	public java.lang.String getRw_1_TGT() {
		return this.rw_1_TGT;
	}

	public void setRw_1_TGT(java.lang.String rw_1_TGT) {
		this.rw_1_TGT = rw_1_TGT;
	}

	public java.lang.String getRw_1_TY() {
		return this.rw_1_TY;
	}

	public void setRw_1_TY(java.lang.String rw_1_TY) {
		this.rw_1_TY = rw_1_TY;
	}

	public java.lang.String getRw_1_TOTAL() {
		return this.rw_1_TOTAL;
	}

	public void setRw_1_TOTAL(java.lang.String rw_1_TOTAL) {
		this.rw_1_TOTAL = rw_1_TOTAL;
	}

	public java.lang.String getRw_2_CONV_CN() {
		return this.rw_2_CONV_CN;
	}

	public void setRw_2_CONV_CN(java.lang.String rw_2_CONV_CN) {
		this.rw_2_CONV_CN = rw_2_CONV_CN;
	}

	public java.lang.String getRw_2_DESC() {
		return this.rw_2_DESC;
	}

	public void setRw_2_DESC(java.lang.String rw_2_DESC) {
		this.rw_2_DESC = rw_2_DESC;
	}

	public java.lang.String getRw_2_DLR_BILL_TO() {
		return this.rw_2_DLR_BILL_TO;
	}

	public void setRw_2_DLR_BILL_TO(java.lang.String rw_2_DLR_BILL_TO) {
		this.rw_2_DLR_BILL_TO = rw_2_DLR_BILL_TO;
	}

	public java.lang.String getRw_2_DLR_CAT() {
		return this.rw_2_DLR_CAT;
	}

	public void setRw_2_DLR_CAT(java.lang.String rw_2_DLR_CAT) {
		this.rw_2_DLR_CAT = rw_2_DLR_CAT;
	}

	public java.lang.String getRw_2_DLR_CODE() {
		return this.rw_2_DLR_CODE;
	}

	public void setRw_2_DLR_CODE(java.lang.String rw_2_DLR_CODE) {
		this.rw_2_DLR_CODE = rw_2_DLR_CODE;
	}

	public java.lang.String getRw_2_CAT() {
		return this.rw_2_CAT;
	}

	public void setRw_2_CAT(java.lang.String rw_2_CAT) {
		this.rw_2_CAT = rw_2_CAT;
	}

	public java.lang.String getRw_2_CODE() {
		return this.rw_2_CODE;
	}

	public void setRw_2_CODE(java.lang.String rw_2_CODE) {
		this.rw_2_CODE = rw_2_CODE;
	}

	public java.lang.String getRw_2_DLR_DEPOT() {
		return this.rw_2_DLR_DEPOT;
	}

	public void setRw_2_DLR_DEPOT(java.lang.String rw_2_DLR_DEPOT) {
		this.rw_2_DLR_DEPOT = rw_2_DLR_DEPOT;
	}

	public java.lang.String getRw_2_DLR_NAME() {
		return this.rw_2_DLR_NAME;
	}

	public void setRw_2_DLR_NAME(java.lang.String rw_2_DLR_NAME) {
		this.rw_2_DLR_NAME = rw_2_DLR_NAME;
	}

	public java.lang.String getRw_2_DLR_REGN() {
		return this.rw_2_DLR_REGN;
	}

	public void setRw_2_DLR_REGN(java.lang.String rw_2_DLR_REGN) {
		this.rw_2_DLR_REGN = rw_2_DLR_REGN;
	}

	public java.lang.String getRw_2_DLR_STATE() {
		return this.rw_2_DLR_STATE;
	}

	public void setRw_2_DLR_STATE(java.lang.String rw_2_DLR_STATE) {
		this.rw_2_DLR_STATE = rw_2_DLR_STATE;
	}

	public java.lang.String getRw_2_DLR_TERR_CODE() {
		return this.rw_2_DLR_TERR_CODE;
	}

	public void setRw_2_DLR_TERR_CODE(java.lang.String rw_2_DLR_TERR_CODE) {
		this.rw_2_DLR_TERR_CODE = rw_2_DLR_TERR_CODE;
	}

	public java.lang.String getRw_2_DLR_TERR_NAME() {
		return this.rw_2_DLR_TERR_NAME;
	}

	public void setRw_2_DLR_TERR_NAME(java.lang.String rw_2_DLR_TERR_NAME) {
		this.rw_2_DLR_TERR_NAME = rw_2_DLR_TERR_NAME;
	}

	public java.lang.String getRw_2_DLR_TYPE() {
		return this.rw_2_DLR_TYPE;
	}

	public void setRw_2_DLR_TYPE(java.lang.String rw_2_DLR_TYPE) {
		this.rw_2_DLR_TYPE = rw_2_DLR_TYPE;
	}

	public java.lang.String getRw_2_GFT_ID() {
		return this.rw_2_GFT_ID;
	}

	public void setRw_2_GFT_ID(java.lang.String rw_2_GFT_ID) {
		this.rw_2_GFT_ID = rw_2_GFT_ID;
	}

	public java.lang.String getRw_2_GFT_TO_CN() {
		return this.rw_2_GFT_TO_CN;
	}

	public void setRw_2_GFT_TO_CN(java.lang.String rw_2_GFT_TO_CN) {
		this.rw_2_GFT_TO_CN = rw_2_GFT_TO_CN;
	}

	public java.lang.String getRw_2_I_STAT() {
		return this.rw_2_I_STAT;
	}

	public void setRw_2_I_STAT(java.lang.String rw_2_I_STAT) {
		this.rw_2_I_STAT = rw_2_I_STAT;
	}

	public java.lang.String getRw_2_LAST_UPDATE() {
		return this.rw_2_LAST_UPDATE;
	}

	public void setRw_2_LAST_UPDATE(java.lang.String rw_2_LAST_UPDATE) {
		this.rw_2_LAST_UPDATE = rw_2_LAST_UPDATE;
	}

	public java.lang.String getRw_2_LY() {
		return this.rw_2_LY;
	}

	public void setRw_2_LY(java.lang.String rw_2_LY) {
		this.rw_2_LY = rw_2_LY;
	}

	public java.lang.String getRw_2_SCH_ID() {
		return this.rw_2_SCH_ID;
	}

	public void setRw_2_SCH_ID(java.lang.String rw_2_SCH_ID) {
		this.rw_2_SCH_ID = rw_2_SCH_ID;
	}

	public java.lang.String getRw_2_TOTAL() {
		return this.rw_2_TOTAL;
	}

	public void setRw_2_TOTAL(java.lang.String rw_2_TOTAL) {
		this.rw_2_TOTAL = rw_2_TOTAL;
	}

	public boolean isDlr_prd_ELIGIBLE_TY() {
		return this.dlr_prd_ELIGIBLE_TY;
	}

	public void setDlr_prd_ELIGIBLE_TY(boolean dlr_prd_ELIGIBLE_TY) {
		this.dlr_prd_ELIGIBLE_TY = dlr_prd_ELIGIBLE_TY;
	}

	public java.lang.String getRw_1_TYPE() {
		return this.rw_1_TYPE;
	}

	public void setRw_1_TYPE(java.lang.String rw_1_TYPE) {
		this.rw_1_TYPE = rw_1_TYPE;
	}

	public java.lang.String getRw_1_UNIT() {
		return this.rw_1_UNIT;
	}

	public void setRw_1_UNIT(java.lang.String rw_1_UNIT) {
		this.rw_1_UNIT = rw_1_UNIT;
	}

	public java.lang.String getRw_2_ADDITIONAL() {
		return this.rw_2_ADDITIONAL;
	}

	public void setRw_2_ADDITIONAL(java.lang.String rw_2_ADDITIONAL) {
		this.rw_2_ADDITIONAL = rw_2_ADDITIONAL;
	}

	public Dealer(java.lang.String id, int dlr_SCH_ID, int dlr_FIN_AN_FLAG,
			java.lang.String dlr_REGN, java.lang.String dlr_DEPOT,
			java.lang.String dlr_STATE, java.lang.String dlr_TERR_CODE,
			java.lang.String dlr_TERR_NAME, java.lang.String dlr_BILL_TO,
			java.lang.String dlr_AC_NO, java.lang.String dlr_AC_NAME,
			java.lang.String dlr_TYPE, java.lang.String dlr_RET,
			int dlr_TOT_CN, int dlr_TOT_BDGT, java.lang.String dlr_MAIN_STATUS,
			double del_TY_VOLUME, int dlr_MAIN_CN,
			boolean dlr_RULES_AND_CONDITION,
			boolean dlr_INFORMATION_IS_COLLECTED, java.lang.String dlr_TERR,
			java.lang.String dlr_SDLR_COUNT, boolean dell_Col,
			java.lang.String dlr_CAT,
			java.util.List<com.kie_pract.bsat_1734.Product> productList,
			boolean dlr_prd_ELIGIBLE_LY, boolean rw_CODE,
			java.lang.String rw_CODE_1, java.lang.String rw_CODE_2,
			java.lang.String rw_2_SEC, java.lang.String rw_2_TYPE,
			java.lang.String rw_2_PRD, java.lang.String rw_2_UNIT,
			java.lang.String rw_2_DATE, java.lang.String rw_2_TGT,
			java.lang.String rw_2_TY, double rw_2_NXT_TGT,
			java.lang.String rw_2_Q_STAT, java.lang.String rw_1_ADDITIONAL,
			java.lang.String rw_1_BASE_TOTAL, java.lang.String rw_1_CONV_CN,
			java.lang.String rw_1_DATE, java.lang.String rw_1_DESC,
			java.lang.String rw_1_DLR_BILL_TO, java.lang.String rw_1_DLR_CAT,
			java.lang.String rw_1_DLR_CODE, java.lang.String rw_1_DLR_DEPOT,
			java.lang.String rw_1_DLR_REGN, java.lang.String rw_1_DLR_NAME,
			java.lang.String rw_1_DLR_STATE,
			java.lang.String rw_1_DLR_TERR_CODE,
			java.lang.String rw_1_DLR_TERR_NAME,
			java.lang.String rw_1_DLR_TYPE, java.lang.String rw_1_GFT_ID,
			java.lang.String rw_1_GFT_TO_CN, java.lang.String rw_1_I_STAT,
			java.lang.String rw_1_LAST_UPDATE, java.lang.String rw_1_SCH_ID,
			java.lang.String rw_1_PRD, java.lang.String rw_1_LY,
			java.lang.String rw_1_Q_STAT, double rw_1_NXT_TGT,
			java.lang.String rw_1_SEC, java.lang.String rw_1_TGT,
			java.lang.String rw_1_TY, java.lang.String rw_1_TOTAL,
			java.lang.String rw_2_CONV_CN, java.lang.String rw_2_DESC,
			java.lang.String rw_2_DLR_BILL_TO, java.lang.String rw_2_DLR_CAT,
			java.lang.String rw_2_DLR_CODE, java.lang.String rw_2_CAT,
			java.lang.String rw_2_CODE, java.lang.String rw_2_DLR_DEPOT,
			java.lang.String rw_2_DLR_NAME, java.lang.String rw_2_DLR_REGN,
			java.lang.String rw_2_DLR_STATE,
			java.lang.String rw_2_DLR_TERR_CODE,
			java.lang.String rw_2_DLR_TERR_NAME,
			java.lang.String rw_2_DLR_TYPE, java.lang.String rw_2_GFT_ID,
			java.lang.String rw_2_GFT_TO_CN, java.lang.String rw_2_I_STAT,
			java.lang.String rw_2_LAST_UPDATE, java.lang.String rw_2_LY,
			java.lang.String rw_2_SCH_ID, java.lang.String rw_2_TOTAL,
			boolean dlr_prd_ELIGIBLE_TY, java.lang.String rw_1_TYPE,
			java.lang.String rw_1_UNIT, java.lang.String rw_2_ADDITIONAL) {
		this.id = id;
		this.dlr_SCH_ID = dlr_SCH_ID;
		this.dlr_FIN_AN_FLAG = dlr_FIN_AN_FLAG;
		this.dlr_REGN = dlr_REGN;
		this.dlr_DEPOT = dlr_DEPOT;
		this.dlr_STATE = dlr_STATE;
		this.dlr_TERR_CODE = dlr_TERR_CODE;
		this.dlr_TERR_NAME = dlr_TERR_NAME;
		this.dlr_BILL_TO = dlr_BILL_TO;
		this.dlr_AC_NO = dlr_AC_NO;
		this.dlr_AC_NAME = dlr_AC_NAME;
		this.dlr_TYPE = dlr_TYPE;
		this.dlr_RET = dlr_RET;
		this.dlr_TOT_CN = dlr_TOT_CN;
		this.dlr_TOT_BDGT = dlr_TOT_BDGT;
		this.dlr_MAIN_STATUS = dlr_MAIN_STATUS;
		this.del_TY_VOLUME = del_TY_VOLUME;
		this.dlr_MAIN_CN = dlr_MAIN_CN;
		this.dlr_RULES_AND_CONDITION = dlr_RULES_AND_CONDITION;
		this.dlr_INFORMATION_IS_COLLECTED = dlr_INFORMATION_IS_COLLECTED;
		this.dlr_TERR = dlr_TERR;
		this.dlr_SDLR_COUNT = dlr_SDLR_COUNT;
		this.dell_Col = dell_Col;
		this.dlr_CAT = dlr_CAT;
		this.productList = productList;
		this.dlr_prd_ELIGIBLE_LY = dlr_prd_ELIGIBLE_LY;
		this.rw_CODE = rw_CODE;
		this.rw_CODE_1 = rw_CODE_1;
		this.rw_CODE_2 = rw_CODE_2;
		this.rw_2_SEC = rw_2_SEC;
		this.rw_2_TYPE = rw_2_TYPE;
		this.rw_2_PRD = rw_2_PRD;
		this.rw_2_UNIT = rw_2_UNIT;
		this.rw_2_DATE = rw_2_DATE;
		this.rw_2_TGT = rw_2_TGT;
		this.rw_2_TY = rw_2_TY;
		this.rw_2_NXT_TGT = rw_2_NXT_TGT;
		this.rw_2_Q_STAT = rw_2_Q_STAT;
		this.rw_1_ADDITIONAL = rw_1_ADDITIONAL;
		this.rw_1_BASE_TOTAL = rw_1_BASE_TOTAL;
		this.rw_1_CONV_CN = rw_1_CONV_CN;
		this.rw_1_DATE = rw_1_DATE;
		this.rw_1_DESC = rw_1_DESC;
		this.rw_1_DLR_BILL_TO = rw_1_DLR_BILL_TO;
		this.rw_1_DLR_CAT = rw_1_DLR_CAT;
		this.rw_1_DLR_CODE = rw_1_DLR_CODE;
		this.rw_1_DLR_DEPOT = rw_1_DLR_DEPOT;
		this.rw_1_DLR_REGN = rw_1_DLR_REGN;
		this.rw_1_DLR_NAME = rw_1_DLR_NAME;
		this.rw_1_DLR_STATE = rw_1_DLR_STATE;
		this.rw_1_DLR_TERR_CODE = rw_1_DLR_TERR_CODE;
		this.rw_1_DLR_TERR_NAME = rw_1_DLR_TERR_NAME;
		this.rw_1_DLR_TYPE = rw_1_DLR_TYPE;
		this.rw_1_GFT_ID = rw_1_GFT_ID;
		this.rw_1_GFT_TO_CN = rw_1_GFT_TO_CN;
		this.rw_1_I_STAT = rw_1_I_STAT;
		this.rw_1_LAST_UPDATE = rw_1_LAST_UPDATE;
		this.rw_1_SCH_ID = rw_1_SCH_ID;
		this.rw_1_PRD = rw_1_PRD;
		this.rw_1_LY = rw_1_LY;
		this.rw_1_Q_STAT = rw_1_Q_STAT;
		this.rw_1_NXT_TGT = rw_1_NXT_TGT;
		this.rw_1_SEC = rw_1_SEC;
		this.rw_1_TGT = rw_1_TGT;
		this.rw_1_TY = rw_1_TY;
		this.rw_1_TOTAL = rw_1_TOTAL;
		this.rw_2_CONV_CN = rw_2_CONV_CN;
		this.rw_2_DESC = rw_2_DESC;
		this.rw_2_DLR_BILL_TO = rw_2_DLR_BILL_TO;
		this.rw_2_DLR_CAT = rw_2_DLR_CAT;
		this.rw_2_DLR_CODE = rw_2_DLR_CODE;
		this.rw_2_CAT = rw_2_CAT;
		this.rw_2_CODE = rw_2_CODE;
		this.rw_2_DLR_DEPOT = rw_2_DLR_DEPOT;
		this.rw_2_DLR_NAME = rw_2_DLR_NAME;
		this.rw_2_DLR_REGN = rw_2_DLR_REGN;
		this.rw_2_DLR_STATE = rw_2_DLR_STATE;
		this.rw_2_DLR_TERR_CODE = rw_2_DLR_TERR_CODE;
		this.rw_2_DLR_TERR_NAME = rw_2_DLR_TERR_NAME;
		this.rw_2_DLR_TYPE = rw_2_DLR_TYPE;
		this.rw_2_GFT_ID = rw_2_GFT_ID;
		this.rw_2_GFT_TO_CN = rw_2_GFT_TO_CN;
		this.rw_2_I_STAT = rw_2_I_STAT;
		this.rw_2_LAST_UPDATE = rw_2_LAST_UPDATE;
		this.rw_2_LY = rw_2_LY;
		this.rw_2_SCH_ID = rw_2_SCH_ID;
		this.rw_2_TOTAL = rw_2_TOTAL;
		this.dlr_prd_ELIGIBLE_TY = dlr_prd_ELIGIBLE_TY;
		this.rw_1_TYPE = rw_1_TYPE;
		this.rw_1_UNIT = rw_1_UNIT;
		this.rw_2_ADDITIONAL = rw_2_ADDITIONAL;
	}

}