package com.kie_pract.bsat_1734;

import java.time.LocalDate;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String prd;
	private int prd_SCH_ID;
	private int prd_BILL_TO;
	private java.lang.String prd_DLR_AC_NO;
	private java.lang.String prd_DLR_TYPE;
	private java.lang.String prd_NAME;
	private java.lang.String prd_CAT;
	private java.lang.String prd_CAT_DESC;
	private java.lang.String prd_GRP;
	private java.lang.String prd_CODE;
	private java.lang.String prd_SHD_CODE;
	private LocalDate prd_INU_DT;
	private java.lang.String prd_UOM;
	private int prd_PCK_SIZE;
	private double prd_VOL;
	private double prd_FNL_VOL;
	private double prd_VAL;
	private double prd_VOL_RW;
	private int prd_FNL_VOL_RW;
	private double prd_VAL_RW;
	private boolean prd_ELIGIBLE_LY;
	private boolean prd_ELIGIBLE_TY;

	public Product() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getPrd() {
		return this.prd;
	}

	public void setPrd(java.lang.String prd) {
		this.prd = prd;
	}

	public java.lang.String getPrd_DLR_AC_NO() {
		return this.prd_DLR_AC_NO;
	}

	public void setPrd_DLR_AC_NO(java.lang.String prd_DLR_AC_NO) {
		this.prd_DLR_AC_NO = prd_DLR_AC_NO;
	}

	public java.lang.String getPrd_DLR_TYPE() {
		return this.prd_DLR_TYPE;
	}

	public void setPrd_DLR_TYPE(java.lang.String prd_DLR_TYPE) {
		this.prd_DLR_TYPE = prd_DLR_TYPE;
	}

	public java.lang.String getPrd_NAME() {
		return this.prd_NAME;
	}

	public void setPrd_NAME(java.lang.String prd_NAME) {
		this.prd_NAME = prd_NAME;
	}

	public java.lang.String getPrd_CAT() {
		return this.prd_CAT;
	}

	public void setPrd_CAT(java.lang.String prd_CAT) {
		this.prd_CAT = prd_CAT;
	}

	public java.lang.String getPrd_CAT_DESC() {
		return this.prd_CAT_DESC;
	}

	public void setPrd_CAT_DESC(java.lang.String prd_CAT_DESC) {
		this.prd_CAT_DESC = prd_CAT_DESC;
	}

	public java.lang.String getPrd_GRP() {
		return this.prd_GRP;
	}

	public void setPrd_GRP(java.lang.String prd_GRP) {
		this.prd_GRP = prd_GRP;
	}

	public java.lang.String getPrd_CODE() {
		return this.prd_CODE;
	}

	public void setPrd_CODE(java.lang.String prd_CODE) {
		this.prd_CODE = prd_CODE;
	}

	public java.lang.String getPrd_SHD_CODE() {
		return this.prd_SHD_CODE;
	}

	public void setPrd_SHD_CODE(java.lang.String prd_SHD_CODE) {
		this.prd_SHD_CODE = prd_SHD_CODE;
	}

	public java.lang.String getPrd_UOM() {
		return this.prd_UOM;
	}

	public void setPrd_UOM(java.lang.String prd_UOM) {
		this.prd_UOM = prd_UOM;
	}

	public int getPrd_FNL_VOL_RW() {
		return this.prd_FNL_VOL_RW;
	}

	public void setPrd_FNL_VOL_RW(int prd_FNL_VOL_RW) {
		this.prd_FNL_VOL_RW = prd_FNL_VOL_RW;
	}

	public boolean isPrd_ELIGIBLE_LY() {
		return this.prd_ELIGIBLE_LY;
	}

	public void setPrd_ELIGIBLE_LY(boolean prd_ELIGIBLE_LY) {
		this.prd_ELIGIBLE_LY = prd_ELIGIBLE_LY;
	}

	public boolean isPrd_ELIGIBLE_TY() {
		return this.prd_ELIGIBLE_TY;
	}

	public void setPrd_ELIGIBLE_TY(boolean prd_ELIGIBLE_TY) {
		this.prd_ELIGIBLE_TY = prd_ELIGIBLE_TY;
	}

	public java.time.LocalDate getPrd_INU_DT() {
		return this.prd_INU_DT;
	}

	public void setPrd_INU_DT(java.time.LocalDate prd_INU_DT) {
		this.prd_INU_DT = prd_INU_DT;
	}

	public int getPrd_SCH_ID() {
		return this.prd_SCH_ID;
	}

	public void setPrd_SCH_ID(int prd_SCH_ID) {
		this.prd_SCH_ID = prd_SCH_ID;
	}

	public int getPrd_BILL_TO() {
		return this.prd_BILL_TO;
	}

	public void setPrd_BILL_TO(int prd_BILL_TO) {
		this.prd_BILL_TO = prd_BILL_TO;
	}

	public int getPrd_PCK_SIZE() {
		return this.prd_PCK_SIZE;
	}

	public void setPrd_PCK_SIZE(int prd_PCK_SIZE) {
		this.prd_PCK_SIZE = prd_PCK_SIZE;
	}

	public double getPrd_VOL_RW() {
		return this.prd_VOL_RW;
	}

	public void setPrd_VOL_RW(double prd_VOL_RW) {
		this.prd_VOL_RW = prd_VOL_RW;
	}

	public double getPrd_VAL_RW() {
		return this.prd_VAL_RW;
	}

	public void setPrd_VAL_RW(double prd_VAL_RW) {
		this.prd_VAL_RW = prd_VAL_RW;
	}

	public double getPrd_VAL() {
		return this.prd_VAL;
	}

	public void setPrd_VAL(double prd_VAL) {
		this.prd_VAL = prd_VAL;
	}

	public double getPrd_FNL_VOL() {
		return this.prd_FNL_VOL;
	}

	public void setPrd_FNL_VOL(double prd_FNL_VOL) {
		this.prd_FNL_VOL = prd_FNL_VOL;
	}

	public double getPrd_VOL() {
		return this.prd_VOL;
	}

	public void setPrd_VOL(double prd_VOL) {
		this.prd_VOL = prd_VOL;
	}

	public Product(java.lang.String id, java.lang.String prd, int prd_SCH_ID,
			int prd_BILL_TO, java.lang.String prd_DLR_AC_NO,
			java.lang.String prd_DLR_TYPE, java.lang.String prd_NAME,
			java.lang.String prd_CAT, java.lang.String prd_CAT_DESC,
			java.lang.String prd_GRP, java.lang.String prd_CODE,
			java.lang.String prd_SHD_CODE, java.time.LocalDate prd_INU_DT,
			java.lang.String prd_UOM, int prd_PCK_SIZE, double prd_VOL,
			double prd_FNL_VOL, double prd_VAL, double prd_VOL_RW,
			int prd_FNL_VOL_RW, double prd_VAL_RW, boolean prd_ELIGIBLE_LY,
			boolean prd_ELIGIBLE_TY) {
		this.id = id;
		this.prd = prd;
		this.prd_SCH_ID = prd_SCH_ID;
		this.prd_BILL_TO = prd_BILL_TO;
		this.prd_DLR_AC_NO = prd_DLR_AC_NO;
		this.prd_DLR_TYPE = prd_DLR_TYPE;
		this.prd_NAME = prd_NAME;
		this.prd_CAT = prd_CAT;
		this.prd_CAT_DESC = prd_CAT_DESC;
		this.prd_GRP = prd_GRP;
		this.prd_CODE = prd_CODE;
		this.prd_SHD_CODE = prd_SHD_CODE;
		this.prd_INU_DT = prd_INU_DT;
		this.prd_UOM = prd_UOM;
		this.prd_PCK_SIZE = prd_PCK_SIZE;
		this.prd_VOL = prd_VOL;
		this.prd_FNL_VOL = prd_FNL_VOL;
		this.prd_VAL = prd_VAL;
		this.prd_VOL_RW = prd_VOL_RW;
		this.prd_FNL_VOL_RW = prd_FNL_VOL_RW;
		this.prd_VAL_RW = prd_VAL_RW;
		this.prd_ELIGIBLE_LY = prd_ELIGIBLE_LY;
		this.prd_ELIGIBLE_TY = prd_ELIGIBLE_TY;
	}

}